[package]
name = "lobbyguard-core"
version = "0.1.0"
edition = "2024"

[dependencies]
etherparse = "0.19.0"
windivert = { version = ">=0.7.0-beta" }
snafu = "0.8.9"
compio = { version = "0.17", features = [
    "runtime",
    "macros",
    "signal",
    "dispatcher"
] }
epserde = "0.11"
