fn_params_layout = "Compressed"
fn_single_line = true
hard_tabs = true
imports_granularity = "Module"
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
tab_spaces = 2