[package]
name = "lobbyguard-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
winio = { git = "https://github.com/compio-rs/winio.git", default-features = false, features = ["winui"] }
snafu = "0.8.9"
etherparse = "0.19.0"
windivert = { version = ">=0.7.0-beta" }
compio = "0.17.0"
