[package]
name = "lobbyguard-cli"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
etherparse = "0.19"
windivert = { version = ">=0.7.0-beta" }
tokio = { version = "1", features = ["full"] }
argh = "0.1"
pcap-file = ">=3.0.0-rc1"

[build-dependencies]
winres = "0.1"
