[package]
name = "lobbyguard-cli"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
etherparse = "0.19.0"
windivert = { version = ">=0.7.0-beta" }
tokio = { version = "1", features = ["full"] }

[build-dependencies]
winres = "0.1"
